from __future__ import annotations

import csv
import hashlib
import json
import re
import unicodedata
from collections import defaultdict
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
CSV_PATH = REPO_ROOT / "data" / "xdu-canteen" / "export" / "xdu-canteen-wechat-text-window-dishes.csv"
ARTICLES_PATH = REPO_ROOT / "data" / "xdu-canteen" / "raw" / "articles.manifest.json"
OUTPUT_PATH = REPO_ROOT / "src" / "data" / "xduWechatTextCanteens.generated.ts"

FOOD_TYPES = {"rice", "noodle", "spicy", "light", "snack", "western", "drink", "vegetarian", "halal", "protein", "local"}
MEAL_PERIODS = {"breakfast", "lunch", "dinner", "late"}
HEAT_LEVELS = {"none", "mild", "medium", "hot"}

FLAVOR_OPTION_EXACT = {
    "三鲜",
    "中辣",
    "千岛类",
    "原味",
    "咖喱味",
    "大",
    "大份",
    "小",
    "小份",
    "干拌",
    "微辣",
    "招牌",
    "汤面",
    "清香",
    "烧烤味",
    "特辣",
    "番茄",
    "红枣",
    "经典",
    "藤椒",
    "酸菜",
    "酸辣",
    "酸辣等口味",
    "金汤",
    "重辣",
    "香辣",
    "香辣味",
    "麻椒",
    "麻辣",
    "黑椒",
    "黑椒味",
    "黑芝麻",
}

SIDE_DISH_EXACT = {
    "米饭",
    "白米饭",
    "米饭等",
    "煎蛋",
    "鸡蛋",
    "火腿",
    "烤肠",
    "烤肠）",
    "培根",
    "肉松",
    "鱼豆腐",
    "加蛋",
    "加面",
    "加粉",
    "配菜",
    "小菜",
    "加菜",
    "各种加菜",
    "各种配菜）",
    "各种配菜",
    "各类配菜",
}

NON_DISH_EXACT = {
    "早餐",
    "午餐",
    "晚餐",
    "早点",
    "午晚餐",
    "晚点",
    "一荤一素",
    "两素",
    "两荤一素",
    "上下滑动查看更多",
    "上滑查看更多",
    "下滑查看更多",
    "滑动查看更多",
    "点击查看更多",
    "查看更多",
}


def main() -> None:
    rows = read_rows()
    articles = read_articles()
    vendors = records_to_vendors(rows, articles)
    source_summary = source_summary_from_rows(rows, articles)

    text = (
        'import type { FoodVendor } from "../domain/food";\n\n'
        "// Auto-generated by tools/xdu-canteen-import/generate_wechat_text_data.py.\n"
        "// Source rows come from WeChat article body text, not OCR image prices.\n\n"
        "export interface WechatTextCanteenSourceSummary {\n"
        '  id: string;\n  campus: FoodVendor["campus"];\n  area: string;\n  floor?: string;\n'
        "  sourceUrl: string;\n  sourceTitle: string;\n  updatedAt: string;\n  imageCount: number;\n"
        "}\n\n"
        f"export const xduWechatTextCanteenSourceSummary: WechatTextCanteenSourceSummary[] = {json_for_ts(source_summary)};\n\n"
        f"export const xduWechatTextCanteenVendors: FoodVendor[] = {json_for_ts(vendors)};\n"
    )
    OUTPUT_PATH.write_text(text, encoding="utf-8", newline="\n")
    dish_count = sum(len(vendor["items"]) for vendor in vendors)
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}: {len(vendors)} vendors, {dish_count} dishes")


def read_rows() -> list[dict[str, str]]:
    with CSV_PATH.open("r", encoding="utf-8-sig", newline="") as file:
        rows = [normalize_row(row) for row in csv.DictReader(file)]
    return [row for row in rows if is_usable_dish(row["dish_name"])]


def normalize_row(row: dict[str, str]) -> dict[str, str]:
    return {key: clean_text(value or "") for key, value in row.items()}


def read_articles() -> dict[str, dict[str, Any]]:
    if not ARTICLES_PATH.exists():
        return {}
    return {article["id"]: article for article in json.loads(ARTICLES_PATH.read_text(encoding="utf-8"))}


def is_usable_dish(name: str) -> bool:
    value = clean_dish_name(name)
    if not value:
        return False
    if value in SIDE_DISH_EXACT or value in NON_DISH_EXACT or value in FLAVOR_OPTION_EXACT:
        return False
    if len(value) <= 1:
        return False
    if is_flavor_option_fragment(value):
        return False
    if re.search(r"电话|扫码|公众号|办公室|出入口|楼梯|窗口|菜单|光盘|节约|浪费|滑动|查看更多|点击|长按|加菜|配菜", value):
        return False
    return True


def records_to_vendors(rows: list[dict[str, str]], articles: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[(row["article_id"], row["window_no"], row["window_name"])].append(row)

    vendors: list[dict[str, Any]] = []
    for key in sorted(grouped):
        group = grouped[key]
        first = group[0]
        article = articles.get(first["article_id"], {})
        vendor_id = slugify(f"{first['article_id']}-{first['window_no']}-{first['window_name']}")
        vendor_location = first["location_hint"] or format_location(first)
        items = records_to_items(group, vendor_id, vendor_location)
        if not items:
            continue
        tags = unique([tag for item in items for tag in item["types"]])
        vendors.append(
            {
                "id": vendor_id,
                "name": f"{first['area']} {first['window_no']}# · {first['window_name']}".replace("  #", " #"),
                "campus": first["campus"],
                "channel": "canteen",
                "area": first["area"],
                "floor": first.get("floor") or article.get("floor") or "",
                "windowNo": first["window_no"],
                "windowName": first["window_name"],
                "locationHint": vendor_location,
                "distanceMinutes": int(article.get("distanceMinutes") or 6),
                "tags": tags,
                "source": "西电后勤公众号 · 正文菜单待校准",
                "sourceUrl": first["source_url"],
                "sourceTitle": first["source_title"],
                "updatedAt": first["updated_at"],
                "sourceMethod": "html-text",
                "reviewStatus": "pending",
                "duplicateCount": sum(int(row.get("duplicate_count") or 1) for row in group),
                "items": items,
            }
        )
    return vendors


def records_to_items(rows: list[dict[str, str]], vendor_id: str, vendor_location: str) -> list[dict[str, Any]]:
    merged: dict[str, dict[str, Any]] = {}
    for row in rows:
        dish_name = clean_dish_name(row["dish_name"])
        if not is_usable_dish(dish_name):
            continue
        key = normalize_key(dish_name)
        current = merged.get(key)
        duplicate_count = int(row.get("duplicate_count") or 1)
        if current:
            current["duplicateCount"] += duplicate_count
            continue
        item_id = slugify(f"{vendor_id}-{dish_name}-{row.get('review_id') or short_hash(dish_name)}")
        item_location = row["location_hint"] or vendor_location
        merged[key] = {
            "id": item_id,
            "name": dish_name,
            "types": parse_types(row["types"], dish_name),
            "heat": parse_heat(row["heat"]),
            "popularity": 0.72,
            "available": parse_available(row["available"], dish_name),
            "description": f"{item_location}，西电后勤公众号正文提取，当前不展示历史价格。",
            "windowNo": row["window_no"],
            "windowName": row["window_name"],
            "locationHint": item_location,
            "sourceUrl": row["source_url"],
            "sourceTitle": row["source_title"],
            "sourceMethod": "html-text",
            "reviewStatus": "pending",
            "parseWarnings": ["wechat-text"],
            "duplicateCount": duplicate_count,
        }
    return sorted(merged.values(), key=lambda item: item["name"])


def source_summary_from_rows(rows: list[dict[str, str]], articles: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    by_article: dict[str, dict[str, str]] = {}
    for row in rows:
        by_article.setdefault(row["article_id"], row)
    summary = []
    for article_id in sorted(by_article):
        row = by_article[article_id]
        article = articles.get(article_id, {})
        summary.append(
            {
                "id": article_id,
                "campus": row["campus"],
                "area": row["area"],
                "floor": row["floor"] or article.get("floor") or "",
                "sourceUrl": row["source_url"],
                "sourceTitle": row["source_title"],
                "updatedAt": row["updated_at"],
                "imageCount": len(article.get("images", [])),
            }
        )
    return summary


def parse_types(value: str, dish_name: str) -> list[str]:
    types = [part for part in split_cell(value) if part in FOOD_TYPES]
    if not types:
        types = infer_types(dish_name)
    return unique(types)


def parse_available(value: str, dish_name: str) -> list[str]:
    periods = [part for part in split_cell(value) if part in MEAL_PERIODS]
    if periods:
        return unique(periods)
    if re.search(r"早餐|早点|豆浆|油条|包子|胡辣汤|豆腐脑|粥|馅饼|手抓饼|饭团", dish_name):
        return ["breakfast", "lunch", "dinner"]
    return ["lunch", "dinner"]


def parse_heat(value: str) -> str:
    return value if value in HEAT_LEVELS else "none"


def split_cell(value: str) -> list[str]:
    return [part.strip() for part in re.split(r"[;；,，、]+", value or "") if part.strip()]


def infer_types(name: str) -> list[str]:
    rules = [
        ("rice", r"饭|米|套餐|盖浇|小碗菜|自选"),
        ("noodle", r"面|粉|米线|馄饨|饺|冒菜|麻辣烫"),
        ("spicy", r"辣|麻|椒|川|酸菜|泡椒|水煮"),
        ("light", r"粥|豆浆|汤|番茄|鸡蛋羹|南瓜"),
        ("snack", r"饼|馍|包|串|饭团|小吃|炸|汉堡|薯条|鸡柳"),
        ("western", r"咖喱|汉堡|披萨|意面|西式|薯条"),
        ("drink", r"奶茶|咖啡|饮料|酸奶|果汁|柠檬|椰奶|豆浆"),
        ("vegetarian", r"素|青菜|土豆|茄子|豆腐|包菜|白菜|西红柿|番茄|韭菜鸡蛋"),
        ("halal", r"清真|牛肉拉面|兰州|新疆|炒米粉"),
        ("protein", r"肉|鸡|鸭|鱼|牛|羊|蛋|排骨|肥肠|虾|猪|肠|培根|里脊"),
        ("local", r"臊子|肉夹馍|凉皮|岐山|油泼|胡辣汤|泡馍|煮馍"),
    ]
    result = [food_type for food_type, pattern in rules if re.search(pattern, name)]
    return unique(result or ["snack"])


def format_location(row: dict[str, str]) -> str:
    parts = [
        row["area"],
        row["floor"],
        f"{row['window_no']}号窗口" if row["window_no"] else "",
        row["window_name"],
    ]
    return " · ".join(part for part in parts if part)


def clean_dish_name(value: str) -> str:
    value = clean_text(value)
    value = value.replace("(", "（").replace(")", "）")
    value = value.strip("、，,;；:：.。|/\\ ")
    value = drop_leading_unmatched_close(value)
    value = drop_unmatched_open_tail(value)
    value = re.sub(r"（([^（）]*)）", replace_parenthetical, value)
    value = value.replace("（", "").replace("）", "")
    value = re.sub(r"\s+", " ", value)
    return value.strip("、，,;；:：.。|/\\ ")


def drop_leading_unmatched_close(value: str) -> str:
    while "）" in value:
        close_index = value.find("）")
        if "（" in value[:close_index]:
            return value
        before = value[:close_index].strip("、，,;；:：.。|/\\ ")
        after = value[close_index + 1 :].strip("、，,;；:：.。|/\\ ")
        if after and is_flavor_option_fragment(before):
            value = after
            continue
        value = f"{value[:close_index]}{value[close_index + 1:]}"
    return value


def drop_unmatched_open_tail(value: str) -> str:
    while value.count("（") > value.count("）"):
        open_index = value.rfind("（")
        if open_index < 0:
            break
        value = value[:open_index].strip("、，,;；:：.。|/\\ ")
    return value


def replace_parenthetical(match: re.Match[str]) -> str:
    content = clean_text(match.group(1))
    return "" if is_flavor_option_fragment(content) else content


def is_flavor_option_fragment(value: str) -> bool:
    text = clean_text(value)
    if not text:
        return False
    text = text.replace("(", "（").replace(")", "）")
    text = text.strip("、，,;；:：.。|/\\（） ")
    text = re.sub(r"(等口味|口味)$", "", text).strip()
    if not text:
        return False
    if text in FLAVOR_OPTION_EXACT:
        return True
    tokens = [token for token in re.split(r"[\s、,，/／+＋;；]+", text) if token]
    return bool(tokens) and all(token in FLAVOR_OPTION_EXACT for token in tokens)


def clean_text(value: str) -> str:
    value = str(value or "").replace("\ufeff", "")
    value = re.sub(r"\s+", " ", value)
    return value.strip()


def normalize_key(value: str) -> str:
    return re.sub(r"[\s·.。()\[\]（）【】,，、;；:：|/\\]+", "", unicodedata.normalize("NFKC", value)).lower()


def slugify(value: str) -> str:
    readable = re.sub(r"[^0-9A-Za-z\u4e00-\u9fff]+", "-", value).strip("-")
    readable = re.sub(r"-{2,}", "-", readable)
    return f"{readable[:72]}-{short_hash(value)}"


def short_hash(value: str) -> str:
    return hashlib.sha1(value.encode("utf-8")).hexdigest()[:8]


def unique(values: list[str]) -> list[str]:
    return list(dict.fromkeys(value for value in values if value))


def json_for_ts(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


if __name__ == "__main__":
    main()
